# Terraform이 자동 생성. 직접 편집하지 말 것 — 다음 apply에서 덮어써짐.
# 재생성: terraform apply (in terraform/environments/dev)

all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /mnt/c/Users/yeope/yeounhyeok/projectWorkspace/SW-HUB/iac/sw-hub-dev.pem

    # RDS 접속 정보 (비밀번호 제외)
    postgres_rds_host: sw-hub-dev-db.c988aqimud6k.ap-northeast-2.rds.amazonaws.com
    postgres_rds_port: 5432
    postgres_rds_database: swhub
    postgres_rds_user: swhub_admin
  children:
    app:
      hosts:
        sw-hub-app-1:
          ansible_host: 54.180.133.91
