---
- name: Apply base runtime configuration
  hosts: app
  become: true
  gather_facts: true

  roles:
    - common
    - ram_optimization
    - docker
    - role: postgres
      tags: [db, postgres]
