---
- name: Apply base runtime configuration
  hosts: app
  become: true
  gather_facts: true

  roles:
    - common
    - ram_optimization
    - role: awscli
      tags: [awscli]
    - docker
    - role: redis
      tags: [cache, redis]
    - role: cloudflared
      tags: [cloudflared, tunnel]
    - role: postgres
      tags: [db, postgres]
